<?php

declare(strict_types=1);

namespace Rbn\Framework\Core\System\Discovery\Engine\Cache;

use Rbn\Framework\Core\System\Paths\Paths;
use Rbn\Framework\Core\Base\Concerns\Data\ResolvesProjectConfigTrait;

/**
 * DiscoveryMapper - Shared Discovery Persistence Manager 💾⚡🛰️
 * 
 * RBN Framework: Centralized storage engine for discovery maps and resolution caches.
 * Ensures high-speed disk persistence across the entire Discovery Cluster.
 */
class DiscoveryMapper
{
    use ResolvesProjectConfigTrait;

    /** @var array Shared resolution map (In-Memory) */
    private static array $resolutionMap = [];

    /** @var bool Flag to check if map is loaded from disk */
    private static bool $mapLoaded = false;

    /** @var bool Flag to track updates for shutdown saving */
    private static bool $isDirty = false;

    /**
     * Get a cached resolution from the map 🔍
     */
    public function get(string $key)
    {
        $this->ensureMapLoaded();
        return self::$resolutionMap[strtolower($key)] ?? null;
    }

    /**
     * Store a resolution in the map 💾
     */
    public function set(string $key, $value): void
    {
        $this->ensureMapLoaded();
        self::$resolutionMap[strtolower($key)] = $value;
        self::$isDirty = true;
    }

    /**
     * Clear the physical discovery map 🧹
     */
    public function clear(): bool
    {
        $mapFile = $this->getMapFilePath();
        if ($mapFile) {
            $driver = new \Rbn\Framework\Core\System\Storage\Drivers\UniversalFileDriver();
            $driver->delete($mapFile);
        }
        self::$resolutionMap = [];
        self::$isDirty = false;
        return true;
    }

    /**
     * Reset in-memory cached map state for dynamic project context switches 🔄
     */
    public static function resetMemory(): void
    {
        self::$resolutionMap = [];
        self::$mapLoaded = false;
        self::$isDirty = false;
    }

    /**
     * Ensures the discovery map is loaded from disk into memory ⚡
     */
    private function ensureMapLoaded(): void
    {
        if (self::$mapLoaded)
            return;

        // [RBN SURVIVAL] Bypass disk loading if paths are not yet initialized 🏛️⚓
        if (!Paths::isInitialized()) {
            return;
        }

        $path = $this->getMapFilePath();
        if ($path && file_exists($path)) {
            try {
                $map = @include $path;
                if (is_array($map)) {
                    self::$resolutionMap = array_filter($map, fn($v) => $v !== null);
                }
            } catch (\Throwable $e) {
                // Dosya okuma veya izin hatasında canlı tarama ile devam et 🛡️
            }
        }

        self::$mapLoaded = true;

        // Auto-save on shutdown if updated
        register_shutdown_function([$this, 'saveMap']);
    }

    /**
     * Saves the current resolution map to disk 💾
     */
    public function saveMap(): void
    {
        if (!self::$isDirty || !Paths::isInitialized())
            return;

        $cacheFile = $this->getMapFilePath();
        if (!$cacheFile) return;

        try {
            $cleanMap = array_filter(self::$resolutionMap, fn($v) => $v !== null);
            $content = "<?php\n\n// RBN Framework Discovery Map - Generated by DiscoveryMapper\nreturn " . var_export($cleanMap, true) . ";";
            $driver = new \Rbn\Framework\Core\System\Storage\Drivers\UniversalFileDriver();
            $driver->write($cacheFile, $content, 'php');
            self::$isDirty = false;
        } catch (\Throwable $e) {
            // Diske yazma engellenirse sessizce koru 🛡️
        }
    }

    /**
     * Get the absolute path to the discovery map file 📂
     */
    private function getMapFilePath(): ?string
    {
        if (!Paths::isInitialized()) {
            return null;
        }
        
        $projectKey = function_exists('project_key') ? project_key() : null;
        if (empty($projectKey) || $projectKey === 'default') {
            $active = function_exists('active_project_key') ? active_project_key() : null;
            if (!empty($active) && $active !== 'default') {
                $projectKey = $active;
            } else {
                return null;
            }
        }
        
        $projectPath = $this->resolveProjectPath($projectKey);
        if (!empty($projectPath) && is_dir($projectPath)) {
            return $projectPath . '/Storage/framework/discovery_map_' . $projectKey . '.php';
        }

        return null;
    }
}
