<?php

declare(strict_types=1);

namespace Rbn\Framework\Core\Services\System\Models;

use Rbn\Framework\Core\Base\Data\BaseConfig;

/**
 * SettingsConfig - Template Registry for System Settings ⚙️🏛️
 * 
 * RBN Framework: Centralizes all default setting keys, types, groups, and default values.
 * Acts as the Single Source of Truth (SSoT) template for multi-project replication.
 */
class SettingsConfig extends BaseConfig
{
    public const NAME = 'RbnSettings';
    public const VERSION = '1.0';

    /**
     * Standard setting templates (Dummy/empty defaults).
     * These will be dynamically provisioned in the DB for new project keys.
     */
    public const DEFAULT_SETTINGS = [
        // --- Appearance Group ---
        [
            'group_key' => 'appearance',
            'setting_key' => 'theme_color_primary',
            'label_tr' => 'Birincil Tema Rengi',
            'label_en' => 'Primary Theme Color',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Sitenin ana renk kodu (örn: #0ea5e9)',
            'help_text_en' => 'Main theme color code (e.g. #0ea5e9)',
            'setting_value' => '#0ea5e9',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 10
        ],
        [
            'group_key' => 'appearance',
            'setting_key' => 'theme_color_secondary',
            'label_tr' => 'İkincil Renk (Gradyan)',
            'label_en' => 'Secondary Theme Color',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Gradyan ve buton geçiş renk kodu',
            'help_text_en' => 'Gradient and transition color code',
            'setting_value' => '#0284c7',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 20
        ],

        // --- Company Group ---
        [
            'group_key' => 'company',
            'setting_key' => 'company-name',
            'label_tr' => 'Firma Adı',
            'label_en' => 'Company Name',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Kurum veya marka adı',
            'help_text_en' => 'Brand or company name',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 10
        ],
        [
            'group_key' => 'company',
            'setting_key' => 'company-slogan',
            'label_tr' => 'Firma Sloganı',
            'label_en' => 'Company Slogan',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Sitede görünecek slogan',
            'help_text_en' => 'Slogan to show on the site',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 20
        ],
        [
            'group_key' => 'company',
            'setting_key' => 'company-map-location',
            'label_tr' => 'Firma Harita Konumu',
            'label_en' => 'Google Map Coordinates',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Google maps koordinatı veya iframe linki',
            'help_text_en' => 'Google maps coordinate or iframe URL',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 30
        ],
        [
            'group_key' => 'company',
            'setting_key' => 'company-favicon',
            'label_tr' => 'Site Favicon',
            'label_en' => 'Site Favicon',
            'field_type' => 'image',
            'field_options' => null,
            'help_text_tr' => 'Tarayıcı sekmesinde görünen favicon simgesi',
            'help_text_en' => 'Favicon icon to show in browser tab',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 40
        ],
        [
            'group_key' => 'company',
            'setting_key' => 'company-logo',
            'label_tr' => 'Firma Logosu',
            'label_en' => 'Company Logo',
            'field_type' => 'image',
            'field_options' => null,
            'help_text_tr' => 'Sitenin ana logosu',
            'help_text_en' => 'Main site logo',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 50
        ],

        // --- Contact Group ---
        [
            'group_key' => 'contact',
            'setting_key' => 'contact-email',
            'label_tr' => 'iletişim Email-1',
            'label_en' => 'Primary Contact Email',
            'field_type' => 'email',
            'field_options' => null,
            'help_text_tr' => 'İletişim sayfalarında gösterilecek ana e-posta adresi',
            'help_text_en' => 'Main contact email address for public pages',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 10
        ],
        [
            'group_key' => 'contact',
            'setting_key' => 'contact-adress',
            'label_tr' => 'İletişim Adres',
            'label_en' => 'Contact Address',
            'field_type' => 'textarea',
            'field_options' => null,
            'help_text_tr' => 'Fiziksel açık adres',
            'help_text_en' => 'Physical store/office address',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 20
        ],
        [
            'group_key' => 'contact',
            'setting_key' => 'contact-phone',
            'label_tr' => 'İletişim Telefon',
            'label_en' => 'Contact Phone',
            'field_type' => 'tel',
            'field_options' => null,
            'help_text_tr' => 'Müşteri hizmetleri / sabit telefon numarası',
            'help_text_en' => 'Customer service phone number',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 30
        ],
        [
            'group_key' => 'contact',
            'setting_key' => 'whatsapp',
            'label_tr' => 'Whatsapp Link',
            'label_en' => 'WhatsApp Link',
            'field_type' => 'whatsapp',
            'field_options' => null,
            'help_text_tr' => 'WhatsApp hızlı iletişim butonu linki veya numarası',
            'help_text_en' => 'WhatsApp click-to-chat link or number',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 40
        ],

        // --- Email Settings Group ---
        [
            'group_key' => 'email',
            'setting_key' => 'email_enabled',
            'label_tr' => 'Email Ana Şalteri',
            'label_en' => 'Enable Outgoing Email',
            'field_type' => 'toggle',
            'field_options' => null,
            'help_text_tr' => 'E-posta sistemini tamamen açar veya kapatır',
            'help_text_en' => 'Toggles global outgoing mail system',
            'setting_value' => 'on',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 10
        ],
        [
            'group_key' => 'email',
            'setting_key' => 'email_contact_address',
            'label_tr' => 'İletişim Email Adresi',
            'label_en' => 'Contact Form Recipient Email',
            'field_type' => 'email',
            'field_options' => null,
            'help_text_tr' => 'İletişim formu mesajlarının gönderileceği e-posta',
            'help_text_en' => 'Recipient email for public contact forms',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 20
        ],
        [
            'group_key' => 'email',
            'setting_key' => 'email_from_address',
            'label_tr' => 'Gönderen Email Adresi',
            'label_en' => 'From Email Address',
            'field_type' => 'email',
            'field_options' => null,
            'help_text_tr' => 'Giden e-postalarda görünecek gönderici adresi (SMTP kullanıcısıyla uyumlu olmalı)',
            'help_text_en' => 'Sender email address in headers (should match SMTP username)',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 30
        ],
        [
            'group_key' => 'email',
            'setting_key' => 'email_from_name',
            'label_tr' => 'Gönderen Adı',
            'label_en' => 'From Name',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Giden e-postalarda görünecek gönderici ismi',
            'help_text_en' => 'Sender name in headers',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 40
        ],
        [
            'group_key' => 'email',
            'setting_key' => 'email_admin_address',
            'label_tr' => 'Admin Email Adresi',
            'label_en' => 'System Admin Email',
            'field_type' => 'email',
            'field_options' => null,
            'help_text_tr' => 'Sistem bildirimleri ve kritik hataların gideceği e-posta',
            'help_text_en' => 'Target email for system diagnostic notifications',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 50
        ],
        [
            'group_key' => 'email',
            'setting_key' => 'contact_email_subject',
            'label_tr' => 'İletişim Email Konusu',
            'label_en' => 'Contact Email Subject',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Form doldurulduğunda giden mailin konusu',
            'help_text_en' => 'Subject for emails sent on contact form submissions',
            'setting_value' => 'Yeni İletişim Formu Mesajı',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 60
        ],
        [
            'group_key' => 'email',
            'setting_key' => 'contact_auto_reply',
            'label_tr' => 'Otomatik Yanıt',
            'label_en' => 'Enable Auto-Reply',
            'field_type' => 'select',
            'field_options' => '1:Aktif|0:Pasif',
            'help_text_tr' => 'Formu dolduran müşteriye otomatik teşekkür e-postası atar',
            'help_text_en' => 'Automatically replies to the sender with a thank you email',
            'setting_value' => '0',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 70
        ],
        [
            'group_key' => 'email',
            'setting_key' => 'contact_auto_reply_subject',
            'label_tr' => 'Otomatik Yanıt Başlığı',
            'label_en' => 'Auto-Reply Subject',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Otomatik yanıt e-postasının konusu',
            'help_text_en' => 'Subject of the auto-reply email',
            'setting_value' => 'Mesajınızı Aldık, Teşekkür Ederiz',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 80
        ],
        [
            'group_key' => 'email',
            'setting_key' => 'smtp_host',
            'label_tr' => 'SMTP Sunucusu',
            'label_en' => 'SMTP Host',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Email sunucu adresi (örn: mail.domain.com veya smtp.gmail.com)',
            'help_text_en' => 'SMTP server address (e.g. smtp.gmail.com)',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 90
        ],
        [
            'group_key' => 'email',
            'setting_key' => 'smtp_port',
            'label_tr' => 'SMTP Portu',
            'label_en' => 'SMTP Port',
            'field_type' => 'number',
            'field_options' => null,
            'help_text_tr' => 'SMTP port numarası (örn: 587 veya 465)',
            'help_text_en' => 'SMTP port number (e.g. 587 or 465)',
            'setting_value' => '587',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 100
        ],
        [
            'group_key' => 'email',
            'setting_key' => 'smtp_username',
            'label_tr' => 'SMTP Kullanıcı Adı',
            'label_en' => 'SMTP Username',
            'field_type' => 'email',
            'field_options' => null,
            'help_text_tr' => 'SMTP kimlik doğrulama kullanıcı adı/email',
            'help_text_en' => 'SMTP authentication username/email',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 110
        ],
        [
            'group_key' => 'email',
            'setting_key' => 'smtp_password',
            'label_tr' => 'Email sunucu şifresi',
            'label_en' => 'SMTP Password',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'SMTP kimlik doğrulama şifresi',
            'help_text_en' => 'SMTP authentication password',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 120
        ],

        // --- Integrations Group ---
        [
            'group_key' => 'integrations',
            'setting_key' => 'google_analytics_code',
            'label_tr' => 'Google Analytics Kodu',
            'label_en' => 'Google Analytics Code',
            'field_type' => 'textarea',
            'field_options' => null,
            'help_text_tr' => 'Google Analytics (gtag.js) izleme kodunun tamamı',
            'help_text_en' => 'Complete Google Analytics (gtag.js) tracking code',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 5
        ],
        [
            'group_key' => 'integrations',
            'setting_key' => 'google_adsense_code',
            'label_tr' => 'Google AdSense Kodu',
            'label_en' => 'Google AdSense Code',
            'field_type' => 'textarea',
            'field_options' => null,
            'help_text_tr' => 'Google AdSense reklam kodunun tamamı',
            'help_text_en' => 'Complete Google AdSense advertising script',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 6
        ],
        [
            'group_key' => 'integrations',
            'setting_key' => 'head_scripts',
            'label_tr' => 'Head Scriptleri',
            'label_en' => 'Head Scripts',
            'field_type' => 'textarea',
            'field_options' => null,
            'help_text_tr' => 'HTML <head> içerisine eklenecek kodlar (Google Analytics, Tag Manager vb.)',
            'help_text_en' => 'Codes to inject in HTML <head> (e.g. Analytics tracking scripts)',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 10
        ],
        [
            'group_key' => 'integrations',
            'setting_key' => 'body_scripts',
            'label_tr' => 'Body Scriptleri',
            'label_en' => 'Body Scripts',
            'field_type' => 'textarea',
            'field_options' => null,
            'help_text_tr' => 'HTML <body> başlangıcına eklenecek kodlar',
            'help_text_en' => 'Codes to inject at the start of HTML <body>',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 20
        ],
        [
            'group_key' => 'integrations',
            'setting_key' => 'footer_scripts',
            'label_tr' => 'Footer Scriptleri',
            'label_en' => 'Footer Scripts',
            'field_type' => 'textarea',
            'field_options' => null,
            'help_text_tr' => 'HTML <body> bitiminden (footer) önce eklenecek kodlar',
            'help_text_en' => 'Codes to inject before closure of HTML <body>',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 30
        ],

        // --- Localization Group ---
        [
            'group_key' => 'localization',
            'setting_key' => 'default_language',
            'label_tr' => 'Varsayılan Dil',
            'label_en' => 'Default Language',
            'field_type' => 'select',
            'field_options' => 'tr:Türkçe|en:English',
            'help_text_tr' => 'Sitenin varsayılan önyüz dili',
            'help_text_en' => 'Default public theme language',
            'setting_value' => 'tr',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 10
        ],
        [
            'group_key' => 'localization',
            'setting_key' => 'date_format',
            'label_tr' => 'Tarih Formatı',
            'label_en' => 'Date Format',
            'field_type' => 'select',
            'field_options' => 'd.m.Y:GG.AA.YYYY|Y-m-d:YYYY-AA-GG|m/d/Y:AA/GG/YYYY',
            'help_text_tr' => 'Sitedeki tarih gösterim biçimi',
            'help_text_en' => 'Visual date formatting pattern',
            'setting_value' => 'd.m.Y',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 20
        ],
        [
            'group_key' => 'localization',
            'setting_key' => 'timezone',
            'label_tr' => 'Zaman Dilimi',
            'label_en' => 'Timezone',
            'field_type' => 'select',
            'field_options' => 'Europe/Istanbul:İstanbul (GMT+3)|UTC:Coordinated Universal Time',
            'help_text_tr' => 'Sistem saati zaman dilimi',
            'help_text_en' => 'System application timezone',
            'setting_value' => 'Europe/Istanbul',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 30
        ],
        [
            'group_key' => 'localization',
            'setting_key' => 'site_currency',
            'label_tr' => 'Para Birimi',
            'label_en' => 'Site Currency',
            'field_type' => 'select',
            'field_options' => 'TRY:Türk Lirası (₺)|USD:Amerikan Doları ($)|EUR:Euro (€)',
            'help_text_tr' => 'Sitede gösterilecek varsayılan para birimi',
            'help_text_en' => 'Default currency display settings',
            'setting_value' => 'TRY',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 40
        ],

        // --- Security Group ---
        [
            'group_key' => 'security',
            'setting_key' => 'remember_me_duration',
            'label_tr' => 'Beni Hatırla Süresi',
            'label_en' => 'Remember Me Duration',
            'field_type' => 'number',
            'field_options' => null,
            'help_text_tr' => 'Beni hatırla seçildiğinde çerezin ömrü (Gün bazında)',
            'help_text_en' => 'Lifespan of session cookie on checking remember me (in days)',
            'setting_value' => '30',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 10
        ],
        [
            'group_key' => 'security',
            'setting_key' => 'session_timeout',
            'label_tr' => 'Oturum Süresi',
            'label_en' => 'Session Timeout',
            'field_type' => 'number',
            'field_options' => null,
            'help_text_tr' => 'İşlem yapılmayan oturumların kapanma süresi (Dakika)',
            'help_text_en' => 'Minutes before inactive session is expired',
            'setting_value' => '60',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 20
        ],

        // --- SEO Group ---
        [
            'group_key' => 'seo',
            'setting_key' => 'meta-title',
            'label_tr' => 'Meta Başlık',
            'label_en' => 'Meta Title',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Ana sayfa SEO başlığı',
            'help_text_en' => 'Home page SEO meta title',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 10
        ],
        [
            'group_key' => 'seo',
            'setting_key' => 'meta-description',
            'label_tr' => 'Meta Açıklama',
            'label_en' => 'Meta Description',
            'field_type' => 'textarea',
            'field_options' => null,
            'help_text_tr' => 'Arama motorları için özet site açıklaması',
            'help_text_en' => 'Brief website description in search engines',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 20
        ],
        [
            'group_key' => 'seo',
            'setting_key' => 'meta-keywords',
            'label_tr' => 'Anahtar Kelimeler',
            'label_en' => 'Meta Keywords',
            'field_type' => 'textarea',
            'field_options' => null,
            'help_text_tr' => 'Arama motorları anahtar kelimeleri (virgülle ayırın)',
            'help_text_en' => 'Comma separated meta keywords',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 30
        ],
        [
            'group_key' => 'seo',
            'setting_key' => 'og-title',
            'label_tr' => 'OG Başlık',
            'label_en' => 'OpenGraph Title',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Sosyal medyada paylaşım esnasında çıkacak başlık',
            'help_text_en' => 'Title displayed when sharing link on social media',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 40
        ],
        [
            'group_key' => 'seo',
            'setting_key' => 'og-description',
            'label_tr' => 'OG Açıklama',
            'label_en' => 'OpenGraph Description',
            'field_type' => 'textarea',
            'field_options' => null,
            'help_text_tr' => 'Sosyal paylaşımlarda çıkacak site açıklaması',
            'help_text_en' => 'Description displayed when sharing link on social media',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 50
        ],
        [
            'group_key' => 'seo',
            'setting_key' => 'og-image',
            'label_tr' => 'Open Graph Resim',
            'label_en' => 'OpenGraph Image',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Paylaşılan link görseli URL adresi',
            'help_text_en' => 'Image URL displayed on social sharing card',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 60
        ],
        [
            'group_key' => 'seo',
            'setting_key' => 'og-type',
            'label_tr' => 'Open Graph Tip',
            'label_en' => 'OpenGraph Type',
            'field_type' => 'select',
            'field_options' => 'website:Website|article:Article|book:Book',
            'help_text_tr' => 'Paylaşılan içeriğin semantik türü',
            'help_text_en' => 'Semantic type of content to display in social cards',
            'setting_value' => 'website',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 70
        ],
        [
            'group_key' => 'seo',
            'setting_key' => 'og-locale',
            'label_tr' => 'Open Graph Dil',
            'label_en' => 'OpenGraph Locale',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Sosyal paylaşım yerelleştirme kodu (örn: tr_TR)',
            'help_text_en' => 'Social locale code (e.g. tr_TR)',
            'setting_value' => 'tr_TR',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 80
        ],

        // --- Social Media Group ---
        [
            'group_key' => 'social',
            'setting_key' => 'facebook',
            'label_tr' => 'Facebook Adresi',
            'label_en' => 'Facebook URL',
            'field_type' => 'url',
            'field_options' => null,
            'help_text_tr' => 'Facebook profil/sayfa linki',
            'help_text_en' => 'Facebook profile or page link',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 10
        ],
        [
            'group_key' => 'social',
            'setting_key' => 'twitter',
            'label_tr' => 'Twitter Adresi',
            'label_en' => 'Twitter URL',
            'field_type' => 'url',
            'field_options' => null,
            'help_text_tr' => 'Twitter profil linki',
            'help_text_en' => 'Twitter profile link',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 20
        ],
        [
            'group_key' => 'social',
            'setting_key' => 'instagram',
            'label_tr' => 'Instagram Adresi',
            'label_en' => 'Instagram URL',
            'field_type' => 'url',
            'field_options' => null,
            'help_text_tr' => 'Instagram profil linki',
            'help_text_en' => 'Instagram profile link',
            'setting_value' => '',
            'required_role' => 'admin',
            'is_active' => 1,
            'order_num' => 30
        ],

        // --- System Internals Group (Developer Tools) ---
        [
            'group_key' => 'system',
            'setting_key' => 'seo-report',
            'label_tr' => 'SEO Check-Up Raporu',
            'label_en' => 'SEO Check-Up Report',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Site içi SEO tarama rapor sonuçları',
            'help_text_en' => 'Local search engine audit status report',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 10
        ],
        [
            'group_key' => 'system',
            'setting_key' => 'seo-advice',
            'label_tr' => 'SEO Yapay Zeka Tavsiyesi',
            'label_en' => 'SEO Artificial Intelligence Recommendations',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Kritik iyileştirme tavsiyeleri',
            'help_text_en' => 'Critical AI optimization suggestions',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 20
        ],
        [
            'group_key' => 'system',
            'setting_key' => 'seo-gemini-advice',
            'label_tr' => 'Gemini AI SEO Analizi',
            'label_en' => 'Gemini AI SEO Audit',
            'field_type' => 'textarea',
            'field_options' => null,
            'help_text_tr' => 'Gelişmiş Gemini LLM analizleri',
            'help_text_en' => 'Advanced semantic reviews by Gemini AI',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 30
        ],
        // --- Google AdSense Group ---
        [
            'group_key' => 'integrations',
            'setting_key' => 'adsense_status',
            'label_tr' => 'Reklam Yayın Durumu',
            'label_en' => 'AdSense Status',
            'field_type' => 'boolean',
            'field_options' => null,
            'help_text_tr' => 'Tüm sitedeki reklam yayınını tek hamleyle açıp kapatabilirsiniz.',
            'help_text_en' => 'Toggles ad serving across the entire site.',
            'setting_value' => '0',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 10
        ],
        [
            'group_key' => 'integrations',
            'setting_key' => 'adsense_client_id',
            'label_tr' => 'AdSense Yayıncı Kimliği',
            'label_en' => 'AdSense Client ID',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Google AdSense hesabınızın yayıncı kimliğini girin (ca-pub-xxxxxxxxxxxxxxxx).',
            'help_text_en' => 'Enter your unique publisher ID.',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 20
        ],
        [
            'group_key' => 'integrations',
            'setting_key' => 'ads_slot_feed',
            'label_tr' => 'Akış İçi Grid Reklam Slotu',
            'label_en' => 'In-Feed Grid Ad Slot',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Blog listeleme sayfalarında kartların arasında görüntülenecek slot.',
            'help_text_en' => 'Slot ID for in-feed grid layout.',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 30
        ],
        [
            'group_key' => 'integrations',
            'setting_key' => 'ads_slot_content_top',
            'label_tr' => 'Yazı Başı Reklam Slotu',
            'label_en' => 'Article Top Ad Slot',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Blog detay sayfasında içeriğin giriş paragrafından sonra görüntülenecek slot.',
            'help_text_en' => 'Slot ID for top of article content.',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 40
        ],
        [
            'group_key' => 'integrations',
            'setting_key' => 'ads_slot_content_bottom',
            'label_tr' => 'Yazı Sonu Reklam Slotu',
            'label_en' => 'Article Bottom Ad Slot',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Blog detay sayfasında içeriğin altında görüntülenecek slot.',
            'help_text_en' => 'Slot ID for bottom of article content.',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 50
        ],
        [
            'group_key' => 'integrations',
            'setting_key' => 'ads_slot_sidebar',
            'label_tr' => 'Kenar Çubuğu Reklam Slotu',
            'label_en' => 'Sidebar Ad Slot',
            'field_type' => 'text',
            'field_options' => null,
            'help_text_tr' => 'Blog detay sayfalarında sağ kenar çubuğunda görüntülenecek slot.',
            'help_text_en' => 'Slot ID for article sidebar.',
            'setting_value' => '',
            'required_role' => 'developer',
            'is_active' => 1,
            'order_num' => 60
        ]
    ];
}
